### ISSUE TITLE
Infinite loop while running ember install ember-redux

### ISSUE THREAD

**Issue by bstro** [ember-redux/ember-redux#109]
**Problem**
Running `ember install ember-redux` yields the [following output](https://gist.github.com/bstro/88e56e62a9d4e2e41d5256a46097fcbb). Note that this output is recursive. It keeps attempting to install the addon's dependencies over and over. Also note the version arrays logged end up repeating with duplicate values like `[ '1.3.0', '1.3.0', '1.3.0' ]`. This occurs infinitely.

node: `4.4.3`
ember-cli: `2.4.3`
ember: `2.4.5`

This may be related to https://github.com/ember-redux/ember-redux/issues/108

**Comment by toranb** [comment]
@bstro interesting - give the solution I mentioned in #108 a try and report back. This would certainly be the first time I've seen/or heard of a recursive `ember install` here :)

**Comment by bstro** [comment]
I gave up on this, can't seem to get this working in my project. Installed the addons (and addons of addons) manually per your suggestion in #108. Thanks!

**Comment by toranb** [comment]
@bstro oh well I'm happy to help troubleshoot it a fair bit - I wasn't sure if giving up was required just yet :) 

The first question I had "is this an ember-cli v2.4.3 issue?" was quickly confirmed this morning as I just spun up a new app and got the same issue you found (using node v6.10 and node v4.5.0).

The next question "why" might take a little more time (unsure if it's a break in the final release of that 2.4X or something else). So to speed things up and provide a workaround I decided to try this on the very next bump - ember-cli v2.5.1 and wouldn't you know it ... busted in that version also (using both node 6.10 and 4.5)

Finally I flipped over to ember-cli v2.6.2 and all was working fine (tested with node v4.5.0). Not sure if an ember-cli upgrade is possible/ in scope for this process but I can say it's likely the simplest solution/workaround at the moment. If you are truly stuck on 2.4.3 let me know and I'll see if I can't investigate further - this is def a regression as I've been able to install `ember-redux` without issue on older versions of the cli (sorry for the breakdown here)

**Comment by bstro** [comment]
Looking into whether an upgrade is a possibility, but I'm trying not to blow the scope of my project open even further, so I'm leaning towards no, for the time being. Will update if I discover otherwise.

**Comment by toranb** [comment]
@bstro not a problem - totally skipped over the most simple solution earlier (just npm install each dependency - omit the `ember install` step altogether)

That should unblock you for now - still leaving this open to investigate further at some point/ and let others know they are not alone if they run into this bug :)

**Comment by toranb** [comment]
Closing this out for now - I don't have any immediate plans to fix this and I don't hear it holding others back beyond this 1 issue
