### ISSUE TITLE
RFC: Export route and connect from addon root.

### ISSUE THREAD

**Issue by brettburley** [ember-redux/ember-redux#112]
# Summary
The addon root (`addon/index.js`) should export the public API methods for `ember-redux`. The two public methods, `route` and `connect` would be exported so that they could be used in a consuming app via:
```
import { route, connect } from 'ember-redux';
```

# Motivation
Currently the `route` and `connect` functions are exported as default functions from `ember-redux/route` and `ember-redux/components/connect`. The connect function is not really a component, so importing it from a components directory is a bit of a misnomer. More importantly, many other popular ember addons have standardized on exporting their main APIs from their root (e.g. `ember-concurrency`, `ember-data`).

This makes the imports short and memorable, and clarifies which files and methods are part of the public api.

# Detailed Design
We would move the `connect.js` file into `addon` to live alongside the existing `route.js`. The directory structure would look like:
```
addon/index.js
addon/connect.js
addon/route.js
```
The `addon/index.js` file would simply import and re-export the `connect` and `route` files. 

Additionally, we can maintain a file at `addon/components/connect.js` which would import from `addon/connect.js` and re-export with a console deprecation message directing folks using the addon to update their imports. I expect updating the import statements should be very straightforward, and should be possible in a bulk find & replace in almost all cases. At some future version, we can completely remove the old `addon/components/connect.js` file completely.

# Alternatives
Don't make any changes and leave the files where they are.

**Comment by toranb** [comment]
@brettburley great write up - no objections here. I assume we will move ahead w/ your PR next week if we don't get any push back

**Comment by toranb** [comment]
@brettburley well it's been a solid month and then some - the final decision looks/feels like a yes on this. I'll close this out and we can move forward in that PR you have up
