### ISSUE TITLE
Question -- how combine reducers in ember-redux?

### ISSUE THREAD

**Issue by skitterm** [ember-redux/ember-redux#115]
I saw examples of combining reducers over in the redux.js.org [docs](http://redux.js.org/docs/basics/Reducers.html#splitting-reducers). I was wondering how to go about this in Ember redux? For this example, I have a `settings` and a `users` reducer, that will manage those pieces of the state respectively, so the store's state shape should be
```javascript
{
  settings: // settings data,
  users: // users data
}
```

I tried bringing in redux and doing this with `combineReducers`, but I got an error -- here are my reducers:
```javascript
// app/reducers/settings.js
const settings = (state, action) => {
  // reducer code here
};

export default {
  settings
}


// app/reducers/users.js
import { combineReducers } from 'redux';
import settings from './settings';
const users = (state, action) => {
  // reducer code here
};

export default combineReducers({
  settings,
  users
})
```
It worked if I switched the exports for the two reducers to be as follows:
```javascript

// settings.js
export default settings

// users.js
export default {
  settings,
  users
}
```

But I wasn't sure if that does what it needs to. The redux docs show a longhand `combineReducers` equivalent like this:
```javascript
// users.js
function rootReducer(state = {}, action) {
  return {
    settings: settings(state.settings, action),
    users: users(state.users, action)
  };
}

export default rootReducer
```
But that didn't work for me either.

What is the `ember-redux` way to combine reducers together to compose a state tree?

**Comment by toranb** [comment]
@skitterm great question! The short version is to add a reducers directory and inside of it an index.js file that simply exports each independent reducer you have in your app/ or addon(s).

For example, In this example app the index.js file pulls in each reducer and simply exports it. 

https://github.com/toranb/ember-addon-redux-style/blob/master/yelp/app/reducers/index.js

Then, inside ember-redux (the service) -we call `combineReducers` using this index.js exported value.

https://github.com/ember-redux/ember-redux/blob/master/app/services/redux.js#L26

We don't layer in a lot of convention compared to vanilla redux but this is one case in which we simply chose to group the reducers together (under 1 directory) and export them as a single dict. This also allowed us to provide a configuration-free store that is wired in the default redux service used by "connected" components (the ones that subscribe to data in the redux store itself).

Any other questions let me know - happy to help :)

**Comment by skitterm** [comment]
Thanks for the quick and thorough response. That does make sense. I prototyped a bit with a deeper state tree, and I realized I'd want to use `combineReducers` at more than just the root level. So I'm explicitly using `combineReducers()` for those non-root-level reducers to bring things together. Would it make sense for the root-level reducer to also use an explicit `combineReducers` so it's consistent throughout?

**Comment by toranb** [comment]
@skitterm so you are suggesting a change to the store itself (meaning we don't do combineReducers for you -it requires the end user to do that in the reducers/index.js file) ?

Or did I misunderstand - also related to your first post. What error do you get trying to use combine elsewhere in your ember app? Just curious :)

**Comment by ssylvia** [comment]
@toranb I agree with @skitterm that we should allow standard redux convention; passing a reducer function to the createStore method. How about just adding a type check, changing the init function to something like:

```js
init() {
    const reducer = typeof reducer === 'function' ? reducers : combineReducers(reducers);
    this.store = createStoreWithMiddleware(reducer);
    setup(this.store);
    this._super(...arguments);
  },
```

**Comment by toranb** [comment]
@ssylvia gotcha  -thanks for the example just as I submitted a reply :)

So this would be backwards compat with people using `ember-redux` today while offering more control for those who want it? The only downside here being that we introduce a little more fragmentation in the 2x series -what else?

Is this something we should eventually deprecate in the 2X series and push toward an explicit combine call for 3X (to avoid the fork/fragmentation issue I mentioned above ^^) ?

cc @brettburley @dbashford @foxnewsnetwork @sandersky

**Comment by ssylvia** [comment]
@toranb A couple upsides I see to allowing the combine reducers:
- Allows users to mix and match root reducers based on route without having to worry if the top level reducer was created with `combineReducers` or left as an object
- Standard redux docs are more relevant as supplemental documentation
- It allow reducers to remain as standard redux reducers if users ever change libraries.

**Comment by foxnewsnetwork** [comment]
@toranb you know, one of the things we really could do for users of this library is to move the majority of `app/services/redux.js` into `addon/services/redux.js` and change the `app/services/redux.js` to just `export { default } from 'ember-redux/services/redux'`, this way, power users of `ember-redux` can more easily customize their redux service.

For example, @ssylvia in his project would be able to resolve his issue by simply overriding init like so:
`ssylvia-project/app/services/redux.js`
```javascript
import Reducks form 'ember-redux/services/redux';

const getReducers = () => { /* find your reducers somehow */ };
export default Reducks.extend({
  init() { 
    this.store = doWhatYouNeedToWithStoreAndMiddleware(getReducers);
  }
});
```

I understand back in the old days of `ember-redux` being dependent on `ember-cli-browserify`, we had no choice but to create the redux service in `app` instead of `addon`, but now that we have switched over to using a proper `ember-cli-node-assets` shim, we should probably move away from using `app`. This way, we could avoid having to cause fragmentation between 2.x and 3.x and, at the same time, expose a way for end users to do whatever perverse thing they'd like to with their reducers, enhancers, and middlewares

**Comment by skitterm** [comment]
For this case, it seems simpler to change `ember-redux` to handle `combineReducers` at the root level out-of-the-box like redux does, instead of the user having to customize and override the addon.

**Comment by brettburley** [comment]
@skitterm I think you have a good point, and I really like the consistency of having to use `combineReducers` even at the top level, since as you identified, (1) you have to use it at the children level as well, (2) it better matches other redux documentation, and (3) it lets you get started by exporting just a single reducer from the `index.js` file.

I do think @foxnewsnetwork's suggestion of putting the service into addon and re-exporting it from the app directory makes sense too, so that folks can override it if they'd like (keeps this addon composable!), but they get great defaults if they don't want to.

**Comment by foxnewsnetwork** [comment]
lol actually, ideally, can't we just do both?

**Comment by toranb** [comment]
I think we are all in agreement that combineReducers will be something you can do yourself and I should have the bandwidth to take this on early next week unless someone else is eager to write the PR this weekend.

About the 2nd ask - pulling the store back into addon ... that has more to do with us including redux-thunk "out of the box" than anything else. @foxnewsnetwork if you are able to spike this out quickly I'd appreciate you taking the time to prove it (I burned a good 2 hours trying to do just that a month or so back with no success).

Thanks for the discussion all!

**Comment by toranb** [comment]
@skitterm @ssylvia @brettburley @foxnewsnetwork I got a PR up for the `combineReducers` enhancement 

https://github.com/ember-redux/ember-redux/pull/119

feedback welcome :)

**Comment by toranb** [comment]
@foxnewsnetwork I spent a few hours hacking today and got this moved from app/ to addon/

https://github.com/ember-redux/ember-redux/pull/120

PR ^^ shows the dirty work had nothing to do w/ thunk and instead everything to do with how the dummy app is loaded / and when. I've worked around this for now in the test-helper and I think this is just an issue for addons that test via the dummy app.

Feedback welcome on this - if people like this we could move ahead once I figure out the remaining 2 tests (patching has thrown a wrench into this particular move). I'll find some time early next week to sort that out

**Comment by toranb** [comment]
With enough persistence anything is possible ;) crushed those 2 patch tests so PR #120 is g2g

**Comment by toranb** [comment]
Some legit rapid iteration this weekend - @foxnewsnetwork passed on some feedback about PR #120 and I tested it w/ an app and it's bust so ... we created PR #121 (took inspiration from the work Thomas did in parallel to make the `createStore` step more extensible in ember-redux)

Thanks for the feedback - looking for additional thoughts when people jump online early next week again

**Comment by toranb** [comment]
@skitterm if you npm install the branch in PR #119 does it work as you expect allowing you to leverage combineReducers? If so, next question to everyone involved is should we update all the docs, examples, twiddle and deprecate the old approach (removing it altogether in 3X)? I imagine the work required to "fix this" is adding 2 lines of code in the reducers/index.js file (for anyone on the 2X version today). Correct me if I'm wrong

**Comment by brettburley** [comment]
I would support updating the documentation to reflect using `combineReducers` explicitly, and eventually deprecating the existing behavior of automatically applying it. 👍

**Comment by skitterm** [comment]
> @skitterm if you npm install the branch in PR #119 does it work as you expect allowing you to leverage combineReducers? 

Yep, it works great.

**Comment by toranb** [comment]
@skitterm this is now up in the v2.5.0 release on npm

Let me know if anyone has issues/ or further questions about `combineReducers` specifically

The store extensibility discussion will continue over in PR #121 for those interested
