### ISSUE TITLE
Preparing for ember-redux v3.0.0

### ISSUE THREAD

**Issue by toranb** [ember-redux/ember-redux#124]
As we upgrade to babel 6 the `ember-redux-shim` dependency will bump to a new major version because it will now [require](https://github.com/ember-redux/ember-redux-shim/pull/22) `transform-object-rest-spread`

While I'm waiting to merge this related addon I thought we could discuss a few changes as we make our way toward the next major release.

The intimate apis `handleChange` and `getAttrs` will both go away (they have deprecation warnings right now). With some discussion it seems we should also add a deprecation to the non `combineReducers` implementation we supported until recently and remove this completely in the next major release.

The RFC @brettburley has up to move the connect/and route imports may be a great candidate (we could add a deprecation warning to make people aware of this and it would likely remain until the v4 version as I hate to break people with a ton of `connect` import statements). @brettburley you have a PR up for this but it may need a rebase/ and I wanted to see if you could add the deprecation warnings you mentioned (still exporting from the current connect/route locations)

The store extension stuff could use additional documentation and work (a few of us are still working through PR #121 and I'm sure this will work itself out in the next week or so).

Anything else we should be thinking of as we start preparing for another major version bump?

**Comment by toranb** [comment]
A quick update - after some discussion it's very possible we will require node v6+ for the next major release (this does seem to work with older versions of ember-cli thankfully). Any feedback regarding this requirement from the community? The slack channel seems to be more vocal but I'd love to hear from others :)

**Comment by SlyDen** [comment]
My project is OK for Node 6+ (I'm on 7+ actually right now). in this case Node is a build dependency (not a runtime) and in most cases it shouldn't be a problem for people to update their build pipeline.

I suspect there can be hard cases when somebody forced to stay on old Node, but they can stick to older release anyways.

**Comment by bstro** [comment]
Does this new version requirement mean we wouldn't be able to use future versions of ember-redux in our apps, most of which are running on v4.4.3?

**Comment by toranb** [comment]
@bstro the next version will only support node 6+ but it may be the case that we maintain the 2x branch for a good 6-12 months after we ship v3.0 if people like yourself want to use the library but can't make the leap from node v4 => v6 just yet.

A few questions for you if you have the time to give me more information about your build

1. what version of ember-cli are you using?
2. what are the blockers you have upgrading from node v4?
3. does your team have any time allocated to upgrading node later this year?
4. what major features are you looking for that are not yet in this addon?

**Comment by toranb** [comment]
![screen shot 2017-06-02 at 7 45 20 am](https://cloud.githubusercontent.com/assets/147411/26726122/76cb1340-4767-11e7-8435-d80abdb574b7.png)

With the announcement of node 8 this past week, I think it's fair to assume node 6+ as a build time dependency at some point in 2017. For now I'm planning to start work on the v3.0 release in July

**Comment by toranb** [comment]
I'm closing this out with plans to move ahead in July supporting only node 6+ (when the v3.0 release is cut and we upgrade all deps to babel 6)
