### ISSUE TITLE
Question -- ember-redux philosophy?

### ISSUE THREAD

**Issue by ssylvia** [ember-redux/ember-redux#125]
I'm coming from a react/redux background and I'm trying to understand the philosophy behind ember-redux. With react-redux, the developer is in charge of creating the store using the Redux. Then you pass your store to the `<Provider store={appStore} />` component which handle the _subscribe_ change handler and passes the updated `state` to the `connect` component. The `connect` component really is just a simple wrapper to organize the properties.

The difference I see with **ember-redux** is that it tries to take over the redux store creation and sets the store up as an ember service.

Correct me if I'm wrong, but ember-redux currently has these requirements:
1. Only a single top-level reducer
2. Reducer must be defined in `app/reducer/index.js`
3. Can only have a single app state (based on 1), not a different app state per route
4. All container components get access to the same (full) app state.

A couple things I have been missing based on my previous work with redux:
1. Cannot pass the initial state to the `createStore` method
2. Cannot specify which reducer to pass to the store. Ideally, I'd like to pass a different set of reducers to each route so they only get the part of the state they need (some routes and reducers may also be lazy-loaded)
3. There is no `replaceReducer` method (http://redux.js.org/docs/api/Store.html#replaceReducer).
4. A way to `merge props` in a container component with passed props from a higher level container component: https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

To provide some context, I'm building an app that is a website builder. There are only a few routes (view, edit, manage-comments, etc.), some of which require only a small subset of the state or a different state altogether. Each user's website is saved as a simple JSON configuration. Part of the JSON is the components used in the website, and each component will have it's own set of reducers. Most of these components get added on load, but I also need the option to dynamically insert reducers to the store as a users adds/removes components from their website in the website editor.

**Comment by toranb** [comment]
Great question! We want to provide some convention (as you would expect in the ember ecosystem) by dropping the developer into the happy path/ pit of success. In theory this provides a much easier ramp up (as the details about store creation/ ember service injection are out of sight out of mind).

For the power user who needs (or simply wants) complete control over the details of store creation/ combing reducers /etc we are working on a [PR](https://github.com/ember-redux/ember-redux/pull/121) that should provide a more robust redux service. This readme from @foxnewsnetwork is something I'm looking at to write up some new docs explaining "how to override" as needed. I'd like to think we are open to feedback if you want to look over that PR/ try out the branch I have up (to see if the extension points we have in place meet your needs).

The core philosophy for this addon could be stated as 3 points

1) we want api compatibility for connect (to enable a drop in replacement of `react-redux`)
2) we want to abstract the details of store creation/ provide a default middleware/ default enhancer to speed up initial development
3) we should allow power users to override the store creation step as needed (PR #121)

The main idea was that if you had a react app today, and had to join a team doing ember you could essentially copy the reducers/actions/middleware directories over and spin up a 100% green field ember-redux app having to write only new components as ember !== react.
