### ISSUE TITLE
Using alternative store creators.

### ISSUE THREAD

**Issue by bstro** [ember-redux/ember-redux#128]
I'd love to use [Reactotron](https://github.com/infinitered/reactotron) with ember-redux in `development` environments. Reactotron has its own special `createStore` method, which you use like so: `const store = Reactotron.createStore(rootReducer, compose(middleware))`

Is there any natural extension point in ember-redux (or can you think of something I can do to work around or with ember-redux) to enable this?

Thanks!

**Comment by toranb** [comment]
@bstro great question! We actually have a PR up that allows you to customize the store construction. 

https://github.com/ember-redux/ember-redux/pull/121

The documentation on on this branch from @foxnewsnetwork

https://github.com/foxnewsnetwork/ember-redux/tree/feature/addonify-redux-service#customizing-the-redux-service

If you could install from the branch using that PR and override the store creation like so... I'd love to know if you have any pain points. One reason we haven't merged that PR yet is that I need to spend some time updating our documentation here (to show it's supported) and to test it out myself. 

```js
import ReduxService from 'ember-redux/services/redux';

export default ReduxService.extend({
  makeStoreInstance({middlewareConfig, reducers, enhancers}) {
    const store = whatever();
    return store;
  }
});
```

**Comment by bstro** [comment]
Excellent, I'll give it a shot and report back. Thanks!

**Comment by toranb** [comment]
@bstro any luck extending this yourself?

**Comment by bstro** [comment]
@toranb was delayed by vacation, going to try to get to it this week or early next! haven't forgotten though :)

**Comment by bstro** [comment]
Unfortunately it looks as though I won't be able to test this out, as it requires ember-cli 2.10.x and we're stuck on 2.4.3 for the time being. :(

**Comment by toranb** [comment]
@bstro that isn't the case here in my repo - Thomas was using a custom AMD shim for `redux-thunk` that required ember-cli v2.10 but we are not :)

**Comment by bstro** [comment]
I might not be firing on all cylinders this monday morning, but I'm attempting to work with the code in this repo, and upon calling `store.getState()`, I am returned a function with the signature: 
```
function (state, action) {
      return combine(state, action);
    }
```
Instead of a function, I should be expecting a pojo containing my redux state.

**Comment by bstro** [comment]
Traced the code above to https://github.com/ember-redux/ember-redux/blob/a312457d2f2a11a47381e250e1e4fbf0d776ea43/addon/reducers/index.js -> realized I need to actually import reducers/enhancers/middlewareConfig myself as they're not getting picked up when extending the ReduxService.

**Comment by bstro** [comment]
Things seem to be working pretty well. The one hiccup I had was not knowing that I needed to import my reducers/enhancers/middleware and refer to those, rather than the ones passed in the options hash to `makeStoreInstance`

**Comment by toranb** [comment]
@bstro ah good catch - yup it's worth me adding that exact example to the documentation site. So you are using that branch - and everything it's g2g extending this yourself? You mind sharing the example store setup you built? I'd love a look at this myself ;)

**Comment by bstro** [comment]
@toranb sure, let me know if you have any questions. The main thing we're doing here is sending the Ember Data store into a middleware creator, which could only be done from the service where the store is created. https://gist.github.com/bstro/54687687fe963e649f4d85aed6ba4823

**Comment by toranb** [comment]
Thank you for sharing - I'm planning to take from this and test out the WIP branch we have up

**Comment by toranb** [comment]
@bstro I'm closing this out for now - we can continue any discussion of the finer points in PR #121
