### ISSUE TITLE
Incompatible with glimmer

### ISSUE THREAD

**Issue by bstro** [ember-redux/ember-redux#130]
On a fresh install of glimmer, (`ember init -b @glimmer/blueprint`), upon running `ember serve`, I encounter the following error:

`app.import is not yet implemented for GlimmerApp`
`Error: app.import is not yet implemented for GlimmerApp`

The error only occurs after running `ember install ember-redux`

```
ember-cli: 2.14.0-beta.2
node: 6.10.3
os: darwin x86

**Comment by toranb** [comment]
This addon only supports ember - I think other people are spiking on a glimmer-redux addon if you want to checkout the glimmer channel on slack

**Comment by toranb** [comment]
I just published glimmer redux if you are still interested 

https://github.com/glimmer-redux/glimmer-redux
