### ISSUE TITLE
ownProps in dispatchToActions

### ISSUE THREAD

**Issue by bstro** [ember-redux/ember-redux#134]
From https://github.com/ember-redux/ember-redux/pull/56
> react-redux does the same thing for mapDispatchToProps, however this is not so easy in Ember. It seems that after actions are defined, they cannot be easily redefined—therefore the action would not update if the attrs changed, as the user would expect. This PR leaves dispatchToActions alone until this can be investigated further.

It would extremely useful to have `ownProps` passed as an argument to `dispatchToActions`. Are there any new developments on this or is it still impractical to redefine the actions on an Ember component?

edit: I would be interested in investigating this further and submitting a PR if there's room for it.

**Comment by toranb** [comment]
@bstro are looking for something like this from the mapDispatch function?

```js
const mapDispatchToProps = (dispatch, ownProps) => {
  return {
    remove: () => {
      dispatch(removeById(ownProps.id));
    }
  };
};
```

We never added ownProps but if you use the `function` keyword today when you write this function you will have access to the component when you use `this`.

```js
var dispatchToActions = function(dispatch) {
  return {
    rate: rating => {
      let selectedId = get(this, 'selectedId');
      let foo = get(this, 'attrs.foo');
      console.log(foo);
      let params = {
        method: 'POST',
        body: JSON.stringify({rating: rating})
      };
      return fetch(`/api/restaurants/${selectedId}`, params)
        .then(fetched => fetched.json())
        .then(response => dispatch({
          type: 'RESTAURANTS:RATE',
          response: response.restaurants
        }));
    }
  };
};

var stateToComputed = (state) => {
  return {
    reviews: getReviews(state),
    selectedId: getSelectedId(state)
  };
};

export default connect(stateToComputed, dispatchToActions)(Ember.Component);
```

**Comment by bstro** [comment]
Oh. Nice. Maybe not necessary then.

**Comment by toranb** [comment]
@bstro I've found this unlocks just about everything but it's clearly not well documented. If you get comfortable using this and want to write up a section for the docs ... that may help better surface this tribal knowledge :)

**Comment by bstro** [comment]
I'm on it!
