### ISSUE TITLE
Any examples/info regarding testing reducers?

### ISSUE THREAD

**Issue by benoror** [ember-redux/ember-redux#137]
title says it all 😄

**Comment by erkarl** [comment]
@benoror perhaps this is helpful:
https://github.com/erkarl/fronthat/blob/master/tests/unit/reducers/jobs-test.js

**Comment by toranb** [comment]
@benoror a few more examples from the yelp clone I hacked together a while back

https://github.com/toranb/ember-redux-yelp/blob/master/tests/unit/reducers/results-test.js

**Comment by benoror** [comment]
Awesome, thanks @erkarl @toranb! Shall we add some documentation to the README? This is so simple that maybe just linking those examples would be enough. Thoughts?

**Comment by toranb** [comment]
@benoror I think a single ember twiddle that shows how to test a reducer is a good start. This could then be added to the examples section of the documentation website.

Did you find the examples/ or docs part of the public website useful as a beginner?

http://www.ember-redux.com/examples/

**Comment by benoror** [comment]
@toranb I missed the yelp tests examples tbh, as these are not visible in the Twiddle, I think those tests are good enough and should be mentioned somewhere

**Comment by toranb** [comment]
@benoror I'm working on a new example app that I'll include on the website soon. This will show how you might ...

- reducers (unit test)
- selectors (unit test)
- components (integration test)
  - async (ember-cli-mirage)
  - middleware (redux saga)
  - reducers

**Comment by benoror** [comment]
@toranb u're awesome mate!

**Comment by toranb** [comment]
@benoror 

https://github.com/toranb/redux-saga-testing-example/commit/e8a0f48ca0a48e589fe90dd2713045961c1c90e7

^^ the example app above shows everything you asked about. I'm closing this issue out as I've got a PR up to merge that link into the website examples page. If you need anything else or have questions let me know
