### ISSUE TITLE
stateToComputed does not work with class based components

### ISSUE THREAD

**Issue by km-smith** [ember-redux/ember-redux#143]
We started to migrate our components to use ES2015 classes and while doing so discovered ember-redux connected components do not work correctly when provided a class rather than an Ember object based component. Below is some sample code where stateToComputed does not seem to correctly setup the computed properties.

```javascript
import Component from '@ember/component';
import { argument } from '@ember-decorators/argument';
import { required } from '@ember-decorators/argument/validation';
import { optional, type } from '@ember-decorators/argument/type';
import { connect } from 'ember-redux';
import layout from '../templates/components/connected-record';

const getCompiledRecord = (state, recordId, recordType) => {
  if (recordId && recordType) {
    return state.db[recordType][recordId];
  }

  return null;
};

const stateToComputed = (state, { recordId, recordType }) => ({
  record: getCompiledRecord(state, recordId, recordType),
});

class ConnectedRecord extends Component {
  layout=layout;

  @argument
  @required
  @type(optional('string'))
  recordId;

  @argument
  @required
  @type(optional('string'))
  recordType;
}

export default connect(stateToComputed, {})(ConnectedRecord);
```

**Comment by toranb** [comment]
@km-smith great find! I’ll see if I can’t solve this by Friday :)

**Comment by pzuraq** [comment]
@toranb pinged me on Slack about this, I do think we may be able to work out a temporary solution, but because ember-redux extends classes to connect them it may end needing to wait until that fuctionality has been fixed per the ES classs RFC

**Comment by toranb** [comment]
@km-smith I've started the work to support ES2015 class syntax in PR #144 

I've got about 4 missing integration tests at the moment but I could use your help to manually test what I did deliver. Yarn/or npm install from the branch named `branches/testClazz` and let me know if you bump into any issues. The acceptance test I've got in place now gives me some confidence that basic redux functionality is solid, the constructor works and actions bubble as they did with classic ember object.

I'm not yet using es2015 class syntax myself and without first reading the RFC @pzuraq mentioned^ I'm hesitant to ship this implementation. That said, if you are truly ready and want to provide feedback as someone on the bleeding edge :) I think that branch will get you a good long way as-is.

I plan to sync up with @pzuraq after the holiday to better understand any gotchas we might face going forward. The _magic_ involved is a simply look up for `extend` as shown below. If this works today/and after the RFC work lands we could ship this without issue but I'd like a little more time to soak on this and get community feedback. I also don't _love_ this prototype hacking conditional but if it allows teams to migrate toward es2015 syntax we could eventually deprecate ember object allowing us to remove the cruft at some point in the future.

```js
export default (stateToComputed, dispatchToActions=() => ({})) => {
  return IncomingComponent => {
    const WrappedComponent = IncomingComponent || Component;

    if (WrappedComponent.hasOwnProperty('extend')) {
      return wrapEmberObject(stateToComputed, dispatchToActions, WrappedComponent);
    }else{
      return wrapEs2015Class(stateToComputed, dispatchToActions, WrappedComponent);
    }
  };
};
```

If you have any other questions just reach out.

**Comment by km-smith** [comment]
Thanks for the speedy fix. I'll give the feature branch a shot in the next few days and let you know.

**Comment by toranb** [comment]
@km-smith I'm happy to report that my es2015 class syntax feature branch is solid and will get merged early next week (pending a quick look from @pzuraq at some point). Have you had any time to test this out yet? If not look for a v3.1.0 release before the end of the month ;)

**Comment by toranb** [comment]
@km-smith I'm closing this out now that we have support for es2015 class syntax :)

Install ember-redux v3.1.0 and give it a try this week/or next if you have the bandwidth! Thanks again for helping drive this feature last month!

**Comment by km-smith** [comment]
I upgraded to the latest(3.1.0) and everything is working again. Thanks for the quick fix.
