### ISSUE TITLE
Add a link to the Source of the Reddit clone to the homepage

### ISSUE THREAD

**Issue by benshine** [ember-redux/ember-redux#147]
While watching the rad intro video on ember-redux.com I wanted to follow along with the code, but couldn't quite find it. In #146  I'm adding a link to the examples page; I would also like that link on the homepage underneath the video.

**Comment by toranb** [comment]
Right on! I just merged the PR to add the `reddit clone` link up to our examples listing. About the link under the video ... assuming you don't mind tinkering in the website html/css :) see what you can come up with and I'll give it a look

**Comment by toranb** [comment]
@benshine thanks again for the great PRs this week! I love the website !!! If you are at EmberConf next month let me know so I can thank you in person!!
