### ISSUE TITLE
http://www.ember-redux.com/guides/

### ISSUE THREAD

**Issue by joshmccall221** [ember-redux/ember-redux#151]
Maybe mention of mirage before it is referenced in fetch example. 

As I was reading this, I wondered "where might this data be coming from?". 

I understand mirage is outside scope of this doc but is later referenced and assumed in place. Maybe a note in the dependencies.  

Assign this to me and I can do a PR.

**Comment by toranb** [comment]
Ah, fair point! I had MIRAGE in as a baseline commit assuming people could checkout that commit if they had any questions. That said, to the non ember developer this might very well be `magic` and less than helpful as you suggest. Maybe we could mention the PR w/ a link saying something basic like "checkout this commit and ember-cli-mirage for more details about how we fake this `fetch` response"

I'm happy to have you submit some ideas and we can land something in both the JavaScript/TypeScript guides

**Comment by toranb** [comment]
@joshmccall221 I'm closing this out today for inactivity. I've been working on other things and soon I'll be pushing a reboot of the JS/TS guides
