### ISSUE TITLE
Update guides to ember 3.2

### ISSUE THREAD

**Issue by toranb** [ember-redux/ember-redux#156]
Just making a note for myself or anyone who may be interested in helping out

1) update the guides app for JavaScript and TypeScript (including the latest ember-cli-typescript)
2) take the new code samples and update the actual docs to mirror this for anyone following along

**Comment by igbopie** [comment]
Hey @toranb, I think there is an issue using ES2015 classes. The issue happens when trying to execute an action or reading the state from the constructor. At this point of time, connect haven't even been called because, as implemented today, calls super. Where super is my own implementation. By the time my constructor is finished, then connect happens. 

This is what is happening:
MyClass <- Connect

Connect.contructor calls MyClass.constructor
then core.call...

Some how it needs to happen the other way around,  one way to solve this is:

Connect <- MyClass

**Comment by toranb** [comment]
![screen shot 2018-04-17 at 8 48 05 pm](https://user-images.githubusercontent.com/147411/38907281-c918535a-4280-11e8-978e-e1490a00b9dc.png)

I remember writing the es2015 class implementation and fighting this^ myself :(

**Comment by toranb** [comment]
@pzuraq any workaround for this situation or is this just a difference between how ember object and es2015 classes work?

**Comment by igbopie** [comment]
Yes, it is different. Probably we need a different approach. I am writing a new class that can be extended. Also using decorators, will post something here once I got it working :)

**Comment by pzuraq** [comment]
it seems like what you're doing is trying to modify the behavior of the class that's being passed into connect. This is exactly what class decorators and property decorators are being made for, so I would recommend playing around with those a bit to see what you can do with them.

If you want to go the more traditional Redux-y route , it'll likely be a class decorator that receives the `stateToComputed` and `dispatchToActions` values. I do think it would make sense to also look into property decorators though - IANA redux expect, but `connect` always felt like a hack around not having a way to declaratively decorate a class

**Comment by igbopie** [comment]
@pzuraq @toranb I made it work like this: 

```ts
@connect
export default class Container extends Component {

  @store('somereducer.somenumber')
  public somenumber;

  constructor() {
    super();
    this.add();
  }

  public add() {
    this.dispatch({ type: 'ADD' });
  }
}
```

What do you think?

**Comment by toranb** [comment]
@igbopie I'd love the connect decorator if you could alter it to accept the same 2 args we throw in today - stateToComputed/ dispatchToActions

The store decorator could be a discussion for another day. I'm not looking to expand the api just yet as you have it but if you could land a PR w/ a simple connect api that takes 2 args I'll give it a look this week

**Comment by toranb** [comment]
@pzuraq any word on when a 2.0 stable release might happen for `ember-decorators` or what might be blocking it? Just curious if that becomes a dependency of this feature @igbopie is sketching out here :)

https://github.com/ember-decorators/ember-decorators/releases

**Comment by pzuraq** [comment]
Only thing that was blocking it was a bug that happened on Ember canary, we fixed it just recently so I'll be release 2.0 on Friday (my OSS day)

**Comment by toranb** [comment]
@igbopie any progress on the connect decorator you mentioned a few weeks back? As I look ahead to v4.0 of this lib (to support redux 4) I'm thinking that major release would be a great time to add support for this new feature. 

note: If you got busy w/ other stuff that's cool also ;) I just wanted to touch base before I dive into this myself in the coming weeks

**Comment by igbopie** [comment]
Hi!
Sorry I have been busy. The way I have it working is something like this:

```ts
export class ConnectedComponent extends Component {
  @service
  public redux: Redux.Store<any>;

  public stateToComputedProps: ISavedProperty[];

  constructor(...args: any[]) {
    super(...args);

    const stateToComputed = (state: any) =>
    this.stateToComputedProps.reduce((memo: IMap, p: ISavedProperty) => ({
      ...memo,
      [p.classProperty]: get(state, p.storeProperty),
    }), {});
    core.call(this, stateToComputed, {});
  }

  public didUpdateAttrs() {
    this._super();
    update.call(this);
  }

  public willDestroy(...args: any[]) {
    this._super(...args);
    destroy.call(this);
  }

  public dispatch(action: any) {
    const { redux } = this;
    return redux.dispatch(action);
  }
}
```

with this decorator:

```ts
export function store(storeProperty: string) {
  return (clazz: ConnectedComponent, classProperty: string) => {
    const stateToComputedProps = clazz.stateToComputedProps || [];
    stateToComputedProps.push({ storeProperty, classProperty });
    clazz.stateToComputedProps = stateToComputedProps;
  };
}
``` 

the result is something like this:

```ts
export default class SomeContainerComponent extends ConnectedComponent {
  @store('some.redux.store.path')
  public aProperty: string;
  
  anAction() {
    this.dispatch({ type: 'AN_ACTION', payload: 'SOME_PAYLOAD' })
  }
}
```

The reason behind having to extend is that TS was complaining about not having `this.dispatch` function. I made it work with the @connect decorator but TS was not very happy. I decided to go more traditional, create a super component for containers. That was `dispatch` method is directly inherited, no magic. I only use decorators for reading the store, which is awesome!

**Comment by igbopie** [comment]
On the other hand, having the connect decorator like you have proposed should be straight forward!

**Comment by toranb** [comment]
Closing this out now that the guides PR is up. I didn't actually include any es2015 class syntax but I'm still in favor of a solid decorator syntax option for this project if someone gets the bandwidth to test drive one in the future
