### ISSUE TITLE
Update docs website layout

### ISSUE THREAD

**Issue by stormwarning** [ember-redux/ember-redux#160]
Would you be open to a PR with a few refinements to the layout of the docs site? I keep thinking there's a webfont that isn't loading whenever I'm on it 😉

**Comment by toranb** [comment]
Absolutely :) I very much appreciate the help! Thank you in advance !!!

Are you familiar with jekyll ? Any questions just let me know

**Comment by stormwarning** [comment]
No worries!

I have used Jekyll a few times before. One thing I didn't find quite clear was how the docs site is deployed; I didn't see a `gh-pages` branch so I guess you've got something else set up. 

Based on that, would you be open to using [VuePress](https://vuepress.vuejs.org) to generate the docs? I've been using it for a few other projects and it's a delight to use — plus nice to have JS running everything and not require Ruby. No sweat if you're not into it, I've got a start on the updates to the Jekyll site started and should have a PR up soon! 👍

**Comment by toranb** [comment]
@stormwarning tempting ;) but truthfully I'm happy with jekyll/gh-pages at this point. The `docs` directory will be the public website once merged. At some point in the 12/18 months Github made it possible to host your OSS website from the `docs` directory so you can avoid the old school branching model used years ago.

To develop I simply drop into `docs` and spin up jekyll myself. When you feel it looks solid on iPad/ iPhone/ desktop (in a variety of horizontal /vertical widths) I'd push what you have and I'll give it a look. Thanks again!

**Comment by toranb** [comment]
@stormwarning I'm closing this out for now. If you get a PR up at some point I'll be more than happy to give it a look! Thanks again for reaching out
