### ISSUE TITLE
Fully typed custom store example?

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-redux/ember-redux#163]
I have some red squiggles atm: 
![image](https://user-images.githubusercontent.com/199018/40562000-52588a62-602d-11e8-98f9-1a76193f6801.png)

and am having a hard time figuring out what types these things are. 

I'm doing an alternative structure where sagas, reducers, etc, are all grouped by domain concept, rather than by what kind of thing they are.

so, for example: I have a `redux-store/todos/add.ts` which contains the reducers, action creators, and sagas for that behavior (this is just why I'm creating a custom store, so I can use this layout).

As an added bonus, an example of extending the Redux service without using .extend would be good, too. :-D

**Comment by toranb** [comment]
@NullVoxPopuli so if the typing information you are looking for is related to `reducers` and `enhancers` ... 

```js
import ReduxService from 'ember-redux/services/redux';
import reducers from '../reducers/index';
import enhancers from '../enhancers/index';
import middlewares from '../middleware/index';

export default ReduxService.extend({ reducers, enhancers, middlewares });
```

We just pull from the file system so enhancers could be derived by looking at what redux returns from `compose` (the default implementation we ship is below)

```js
import { compose } from 'redux';

var devtools = window.__REDUX_DEVTOOLS_EXTENSION__ ? window.__REDUX_DEVTOOLS_EXTENSION__() : f => f;
export default compose(devtools);
```

In a similar way, reducers return `combineReducers` from redux

```js
import { combineReducers } from 'redux';

const number = ((state, action) => {
  // reducer implementation here
});

export default combineReducers({
    number
});
```

A quick look at the typescript def files for redux and it does appear they have something listed for both. You might dive into that project as I'm not a typescript user at this point sadly :(

https://github.com/reduxjs/redux/blob/master/index.d.ts#L88
