### ISSUE TITLE
Upgrade internal property getting to native getter usage

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-redux/ember-redux#174]
I'm using a sparkles component (which doesn't have this.get), and am getting this error:
```
Uncaught TypeError: this.get is not a function
    at Connect.core (core.js:84)
    at new Connect (es2015-class.js:16)
    at SparklesComponentManager.createComponent (sparkles.js:24)
    at CustomComponentManager.create (glimmer.js:4644)
    at Object.evaluate (runtime.js:1264)
    at AppendOpcodes.evaluate (runtime.js:46)
    at LowLevelVM.evaluateSyscall (runtime.js:2898)
    at LowLevelVM.evaluateInner (runtime.js:2870)
    at LowLevelVM.evaluateOuter (runtime.js:2862)
    at VM.next (runtime.js:4790)
```

Here is my component with connect: 
```ts
import Component from 'sparkles-component';
import { connect } from 'ember-redux';
import { selectors } from 'example-app/src/redux-store/todos';
import { State } from 'example-app/src/redux-store/reducers';

const { list } = selectors;


const stateToComputed = (state: State) => ({
  todos: list(state)
});

@connect(stateToComputed)
export default class TodoListComponent extends Component {}
```

both ember components and sparkles components do not need `this.get` (I think for ember, since version 3.0)

So, updating this would be a very welcome change :)

Here is the PR where service injection was added, if you're curious: https://github.com/rwjblue/sparkles-component/pull/2/files

**Comment by toranb** [comment]
Thanks for the issue! Today sparkles is experimental so I’m not planning to update this addon for compatibility just yet. From the looks of it that style of component in particular needs a tracked friendly connect which exists in my implementation of glimmer redux. If you are up for it I’d encourage looking at how glimmer redux works to spike out an early vNext connect component for glimmer components in ember (via sparkles)

**Comment by NullVoxPopuli** [comment]
Yeah, I just dove in to see what all needed changing. Setting up all the computeds as tracked and all the actions as regular functions seems like it would duplicate a fair amount of code.

Maybe it's best to wait until the sparkles syntax is a little more mainstream

**Comment by toranb** [comment]
@NullVoxPopuli  agreed. I'm keeping a close eye on `@tracked` in ember (stable) and plan to update connect when that lands sometime next year (my best guess at the moment)
