### ISSUE TITLE
Typescript errors for redux https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25109

### ISSUE THREAD

**Issue by BobrImperator** [ember-redux/ember-redux#187]
I've encountered this problem https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25109 after updating typescript in my project.
I've prepared a PR for this, basically I've used Redux's interfaces directly in the declaration file.

**Comment by toranb** [comment]
@BobrImperator v4.0.4 is now up on npm w/ this typescript def file change (thanks for the PR)

https://github.com/ember-redux/ember-redux/releases
