### ISSUE TITLE
Glimmer Component Support

### ISSUE THREAD

**Issue by toranb** [ember-redux/ember-redux#196]
To support Octane this addon needs a different code path for Glimmer Component. I've got a working spike of exactly this in the demo app below. To integrate it further w/ ember redux I'll need to learn how the core team differentiates between glimmer and ember component so we have a reliable way to key off the incoming class.

https://github.com/toranb/octane-interop-redux/commit/51e8fe14802d8bdaf97622fe90a0f616e169dad6

Some additional questions - what class should be the "default" if not specified? I would assume if this goes out the door early next year Ember Component is the better backwards compat option but I'm open to suggestions

**Comment by raghavbk** [comment]
@toranb when are we adding glimmer component support to lib ?

**Comment by toranb** [comment]
@raghavbk hey thanks for reaching out! I put together that spike above when Octane shipped late last year but I need someone else to step up and write the pull request. I don't use ember myself these days and as a result I don't know much about how the ecosystem has evolved over the past year to smoke test this properly.

If you are interested I would greatly appreciate the help and will certainly do my best to ensure it lands/ gets published/ etc. A few things I'd start with if you or anyone else has time to dedicate

1. get consensus from the core team about how to differentiate between an EmberComponent GlimmerComponent so we can keep the library backwards compatible. Today I'd like to provide a different connect like behavior depending on what the person is using.

2. include a connect implementation that works with GlimmerComponent like the one does today for EmberComponent (should be very similar to the spike code referenced above).

3. implement support for factory functions (described in great detail over at the glimmer redux issue) https://github.com/glimmer-redux/glimmer-redux/issues/3

4. test drive out a handful of the happy paths with whatever the appropriate glimmer (component) integration test is

**Comment by toranb** [comment]
Thanks to @raghavbk I'll be including glimmer support side by side w/ class ember as part of ember-redux v6.0 (later in the week)
