### ISSUE TITLE
Add support for @tracked in stateToComputed

### ISSUE THREAD

**Issue by Frank3K** [ember-redux/ember-redux#210]
Currently, the properties defined in `stateToComputed` are not tracked. Therefore, one needs to use `@computed` decorators on properties that are depending on properties from `stateToComputed`. The [current advice](https://github.com/ember-cli/eslint-plugin-ember/blob/8c170398ee68b1cb7ec851bfdde22b06c7df99a9/docs/rules/no-computed-properties-in-native-classes.md) is that `@computed` is not necessary anymore.

Could support for `@tracked` be added to ember-redux? As mentioned [here](https://github.com/ember-redux/ember-redux/issues/174#issuecomment-433903379).

**Comment by toranb** [comment]
@Frank3K I'm definitely open to a transition for the glimmer component internals if someone has the desire to make it happen. I would volunteer my time but I've not been in the ember community for 2 years now myself so I don't honestly have the relevant experience or free time required to re-tool.

If you have the interest and see a real benefit from this effort I'd welcome it and support you along the way.

**Comment by toranb** [comment]
@Frank3K related - I saw Chris Garrett post about this a while back (it appears to be exactly what you are asking for in this issue)

https://github.com/pzuraq/tracked-redux

**Comment by Frank3K** [comment]
Thanks! I'll look into it.
