### ISSUE TITLE
Documentation Upgrade

### ISSUE THREAD

**Issue by dustinfarris** [ember-redux/ember-redux#73]
Barebones TODO list for overhauling the docs (please append/modify as needed):

- [ ] Design
- [ ] Quick Start
  - [ ] Installation
  - [ ] connect example
- [ ] Tutorial
  - [ ] Reducers
  - [ ] Using connect
  - [ ] Middleware
  - [ ] Using with ember-engines
- [ ] API docs
- [ ] Contributing

**Comment by toranb** [comment]
@dustinfarris this looks like a great list - I think the most important part you listed is the API docs for sure (as the connect api is becoming more than a simple func with state as the only param).

The only additional part worth mentioning is a "Guides" section that I'd like to write myself. It's the "building yelp with ember-redux" content I mentioned a while back - I think it shows best the idioms and what a real ember app would look like in the wild. I assume this would be slightly diff than the "tutorial" section you listed above.

What did you have in mind for the "contributing" section? just curious :)

**Comment by dustinfarris** [comment]
@toranb I used "Tutorial" instead of Guides—all the same I think?  Or does the Yelp walkthrough just need it's own section independent of the items I listed?  I'm good for whatever you want here, feel free to adjust the description and put your name next to whatever you're claiming.

re: contributing, I just want to write down our intentions regarding collaborator reviewing/merging, contributor expectations, etc.  nothing too fancy, just collecting thoughts spread over several issues and putting it in writing.  This can be a follow-up PR/discussion once the rest of the docs are in place.

**Comment by foxnewsnetwork** [comment]
Let's also have an "Ecosystem" section where users can come and find out what existing framework tools are available for them to use; perhaps something like:

- [ ] Ecosystem
  - [ ] Screencasts
  - [ ] Example Apps
  - [ ] Articles
  - [ ] Using ember-redux
    - [ ] middleware addons
    - [ ] enhancer addons
    - [ ] data-layer addons
    - [ ] etc.

**Comment by toranb** [comment]
@dustinfarris any chance we kick this off with a more incremental approach at some point before EmberConf? I feel the guides example app I've been hacking on for a good while now is solid given feedback from others in the community. No pressure to ship tomorrow - just wanted to see if we could get this broken down and start shipping weekly in preparation for something more complete around early or mid April (as I'm speaking on ember-redux and hope to drive more adoption following that meetup - similar to the ramp we've seen post ember NYC)

**Comment by dustinfarris** [comment]
@toranb sorry for radio-silence on this—have been dealing with personal stuff.

Yes, I think we can break this down and ship it incrementally.

I am giving another ember-redux talk at ManhattanJS early March and hope to have some progress made by then.

**Comment by dustinfarris** [comment]
I am unable to complete this at this time.
