### ISSUE TITLE
live input update, immutable data, handleChange and Ember rerender

### ISSUE THREAD

**Issue by wooandoo** [ember-redux/ember-redux#97]
Hello,

_It is not a bug, but a feature request._

I have a problem when I update
- a property
- of an item
- of a list in the state

by an input field

```
state
  |- list
       |- * item
```

```hbs
{{#each list as |item|}}
  {{input value=item.value key-press=(action update_item_value)}}
  {{!-- trivial version just to understand my problem --}}
{{/each}}
```

=> the current component and all the parent components and pages are updated, because the state object is updated (it is immutable)

=> and so the {{#each}} helper refreshed the components of the list as well

=> and so the input is refreshed **AND I LOOSE THE CURSOR POSITION !**

Ember is not like ReactJS: without virtual hierarchy to compare, the real components are updated.

In connect > handleChange, we just check if the value of the property was changed, and when a property of an item of a list is changed, the list is changed too, so ember-redux notify this change.

So how to avoid to refresh everything ?

Thanks

**Comment by dustinfarris** [comment]
@wooandoo may I suggest using a changeset?

I blogged about this a while back: https://emberway.io/using-ember-changeset-with-ember-redux-200a7e46c59a#.873ae25fs

It will allow to isolate your in-flight changes without triggering redux updates on every key-press.

**Comment by wooandoo** [comment]
Thanks. I saw your post before I created the issue. ;-)

But I'm not in the same situation: I need to update the state after a key-press (in reality, I defer the update to reduce the number of changes), because I update another component in real time when the input value is updated, not after a submit action.

**Comment by dustinfarris** [comment]
Gotcha.  Ok well this does expose a rough edge.  Will have to give more thought, and I'm not sure the solution lies in ember-redux.  Sounds like we need some sort of "lazy" directive in Ember.

**Comment by toranb** [comment]
@wooandoo just to summarize 

You would prefer a connect api that allows the option to "not subscribe" for changes? If so ... I've been looking at adding something like this (source: react-redux)

https://github.com/reactjs/react-redux/blob/master/src/components/connectAdvanced.js#L67

**Comment by toranb** [comment]
@wooandoo another option (assuming you still want to subscribe for changes in the form component). Have you looked at [ember-one-way-controls](https://github.com/DockYard/ember-one-way-controls) from dockyard? If you look at the readme and search for the word `cursor` it aims to solve this very problem. I remember using strict one way flow with ember (not redux) and having issues with cursor placement (without this addon). Just curious if it solves the immediate issue you are having

**Comment by wooandoo** [comment]
@toranb I'll try your solution: it's the behavior I want !

But the problem is the parent components are updated too, and so the input is rerendered. I'll try to memorize the cursor position maybe in global.

**Comment by sandersky** [comment]
@wooandoo is there a unique identifier property on your list items that would allow you to do something like this:

```handlebars
{{#each list key='myUniqueProperty' as |item|}}
  {{input value=item.value key-press=(action update_item_value)}}
  {{!-- trivial version just to understand my problem --}}
{{/each}}
```

If so, I'm curious if that would solve the issue you are seeing or if the issue still persists.

**Comment by wooandoo** [comment]
Hello,

With the solution of @sandersky, it works:
https://ember-twiddle.com/ebfa40f96ba41659765a09b3715587c1/cffae11937938d033482c0cbb5c83ad85f350797?openFiles=components.my-list.js%2C

The first list has the "key" defined, and not the second one.

Thanks.

Frédéric

**Comment by toranb** [comment]
@wooandoo thanks for creating this twiddle to document the issue/and solution. @sandersky thanks for providing the legit solution to this problem :) #youRawk

**Comment by bstro** [comment]
Hmm. @sandersky 's solution does not work for me, though I don't exactly understand why. I've keyed the necessary each blocks but still lose my cursor position. I'm going to try the changeset route.
